Endpoints:
  metadata:
    name: thelper-external
    namespace: heimdall
  apiVersion: v1
  kind: Endpoints
  subsets:
  - addresses:
    - ip: 10.0.1.0
    ports:
    - port: 8090
Service:
  metadata:
    name: thelper-external
    namespace: heimdall
  apiVersion: v1
  kind: Service
  spec:
    type: ClusterIP
    ports:
    - port: 8090
      targetPort: 8090
Ingress:
  metadata:
    name: thelper-ingress
    namespace: heimdall
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 10G
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      kubernetes.io/ingress.class: nginx
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  spec:
    tls:
    - secretName: wildcard-overcloud-prod-cert
      hosts:
      - thelper.aoldacloud.com
    rules:
    - host: thelper.aoldacloud.com
      http:
        paths:
        - path: /
          backend:
            service:
              port:
                number: 8090
              name: thelper-external
          pathType: Prefix
