---
apiVersion: "v1"
kind: "Endpoints"
metadata:
  name: "thelper-external"
  namespace: "heimdall"
subsets:
- addresses:
  - ip: "10.0.1.0"
  ports:
  - port: 8090
---
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "thelper-external"
  namespace: "heimdall"
spec:
  type: "ClusterIP"
  ports:
  - port: 8090
    targetPort: 8090
---
---
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "thelper-ingress"
  namespace: "heimdall"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10G"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - "thelper.aolda.net"
    secretName: "wildcard-overcloud-prod-cert"
  rules:
  - host: "thelper.aolda.net"
    http:
      paths:
      - pathType: "Prefix"
        path: "/"
        backend:
          service:
            name: "thelper-external"
            port:
              number: 8090
