Endpoints:
  metadata:
    name: gstone-external
    namespace: heimdall
  apiVersion: v1
  kind: Endpoints
  subsets:
  - addresses:
    - ip: 1.1.1.1
    ports:
    - port: 8080
Service:
  metadata:
    name: gstone-external
    namespace: heimdall
  apiVersion: v1
  kind: Service
  spec:
    type: ClusterIP
    ports:
    - port: 8080
      targetPort: 8080
Ingress:
  metadata:
    name: gstone-ingress
    namespace: heimdall
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 10G
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      kubernetes.io/ingress.class: nginx
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  spec:
    tls:
    - secretName: wildcard-overcloud-prod-cert
      hosts:
      - gstone.aoldacloud.com
    rules:
    - host: gstone.aoldacloud.com
      http:
        paths:
        - path: /
          backend:
            service:
              port:
                number: 8080
              name: gstone-external
          pathType: Prefix
