Endpoints:
  metadata:
    name: fine-external
    namespace: heimdall
  apiVersion: v1
  kind: Endpoints
  subsets:
  - addresses:
    - ip: 11.11.11.11
    ports:
    - port: 443
Service:
  metadata:
    name: fine-external
    namespace: heimdall
  apiVersion: v1
  kind: Service
  spec:
    type: ClusterIP
    ports:
    - port: 443
      targetPort: 443
Ingress:
  metadata:
    name: fine-ingress
    namespace: heimdall
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 10G
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      kubernetes.io/ingress.class: nginx
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  spec:
    tls:
    - secretName: wildcard-overcloud-prod-cert
      hosts:
      - fine.aoldacloud.com
    rules:
    - host: fine.aoldacloud.com
      http:
        paths:
        - path: /
          backend:
            service:
              port:
                number: 443
              name: fine-external
          pathType: Prefix
